services:


  book-storage-service:
    build:
      context: .
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://book-storage-db:5432/books
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1111
      - EUREKA_SERVER_URL=http://eureka-service:8761/eureka/



